from datetime import date, datetime, timezone

from fastapi import FastAPI, HTTPException

from app import db

app = FastAPI(title="WexWeather")


@app.get("/data-range")
def data_range():
    return db.get_data_range()


@app.get("/stats/{month}/{day}")
def stats(month: int, day: int):
    return db.get_day_stats(month, day)


@app.get("/summary")
def summary_today():
    """Today's report, generated by last night's job."""
    return daily_summary(datetime.now(timezone.utc).date())


@app.get("/summary/{day}")
def daily_summary(day: date):
    row = db.get_summary(day)
    if row is None:
        raise HTTPException(status_code=404, detail=f"No summary for {day}")
    return row
